-- Tạo database QUANLYTAINGUYENRUNG6
CREATE DATABASE QUANLYTAINGUYENRUNG6;
GO

-- Sử dụng database
USE QUANLYTAINGUYENRUNG6;
GO

-- Tạo bảng CENTRAL
CREATE TABLE CENTRAL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL
);
GO

-- Tạo bảng huyện
CREATE TABLE DISTRICT (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
	ID_CENTRAL INT NOT NULL,
    FOREIGN KEY (ID_CENTRAL) REFERENCES CENTRAL(ID)
);
GO

-- Tạo bảng xã
CREATE TABLE COMMUNE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    ID_DISTRICT INT NOT NULL,
    FOREIGN KEY (ID_DISTRICT) REFERENCES DISTRICT(ID)
);
GO

-- Tạo bảng phân quyền nhóm người dùng
CREATE TABLE ROLES_GROUP (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ROLES BIT NOT NULL -- 0: USER, 1: ADMIN
);
GO

-- Tạo bảng vai trò (user, admin)
CREATE TABLE ROLES (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ROLES BIT NOT NULL -- 0: USER, 1: ADMIN
);
GO

-- Tạo bảng nhóm người dùng (kỹ sư, chuyên viên, kiểm lâm,...)
CREATE TABLE GROUPS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    STATUS BIT NOT NULL, -- TRẠNG THÁI 0: OFF, 1: ON  
    ID_ROLES_GROUP INT NOT NULL, 
    FOREIGN KEY (ID_ROLES_GROUP) REFERENCES ROLES_GROUP(ID)
);
GO

-- Tạo bảng người dùng
CREATE TABLE [USER] (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    STATUS BIT, -- TRẠNG THÁI 0: OFF, 1: ON 
    EMAIL VARCHAR(100),
    PHONE VARCHAR(100) NOT NULL,
    DISPLAY_NAME NVARCHAR(100) DEFAULT 'NO NAME',
    USER_NAME NVARCHAR(100) NOT NULL,
    PASSWORD NVARCHAR(100) NOT NULL,
    ID_COMMUNE INT NOT NULL,
    ID_ROLES INT NOT NULL,
    FOREIGN KEY (ID_ROLES) REFERENCES ROLES(ID),
    FOREIGN KEY (ID_COMMUNE) REFERENCES COMMUNE(ID)
);
GO

-- Tạo bảng trung gian mối quan hệ của user và groups 
CREATE TABLE USER_GROUP (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_USER INT NOT NULL,
    ID_GROUP INT NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES [USER](ID),
    FOREIGN KEY (ID_GROUP) REFERENCES GROUPS(ID)
);
GO

-- Tạo bảng lịch sử tác động
CREATE TABLE IMPACT_HISTORY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TYPE NVARCHAR(100) NOT NULL, -- Loại tác động
    TIME TIME NOT NULL,
    DAY DATE NOT NULL,
    ID_USER INT NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES [USER](ID)
);
GO

-- Tạo bảng lịch sử truy cập
CREATE TABLE ACCESS_HISTORY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    TYPE NVARCHAR(100) NOT NULL, -- Loại truy cập
    TIME TIME NOT NULL,
    DAY DATE NOT NULL,	
    ID_USER INT NOT NULL,
    FOREIGN KEY (ID_USER) REFERENCES [USER](ID)
);
GO

-- Tạo bảng cơ sở sản xuất giống cây trồng
CREATE TABLE PLANT_FACILITY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    STATUS BIT NOT NULL, -- 0: OFF, 1: ON
    ADDRESS NVARCHAR(255) NOT NULL,
    CONTACT_FACE NVARCHAR(100) NOT NULL,
    CONTACT_MAIL NVARCHAR(100) NOT NULL,
    CONTACT_PHONE NVARCHAR(15) NOT NULL,
    ACREAGE FLOAT NOT NULL, -- Diện tích (ha)
    IMAGE_PLANT_BREEDING_FACILITY NVARCHAR(255), -- Bản đồ cơ sở (file ảnh)
    ID_COMMUNE INT NOT NULL,
    FOREIGN KEY (ID_COMMUNE) REFERENCES COMMUNE(ID)
);
GO

-- Tạo bảng danh mục loại giống cây trồng
CREATE TABLE PLANT_TYPE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL, -- Tên giống cây
    TYPE NVARCHAR(100) NOT NULL, -- Loại giống cây (Ví dụ: cây ăn quả, cây công nghiệp)
    PRICE INT NOT NULL, -- Giá bán (VNĐ)
    HEIGHT INT NOT NULL -- Chiều cao cây giống (cm)
);
GO

-- Tạo bảng liên kết cơ sở sản xuất với loại giống cây
CREATE TABLE PLANT_TYPE_PLANT_FACILITY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_PLANT_FACILITY INT NOT NULL,
    ID_PLANT_TYPE INT NOT NULL,
    FOREIGN KEY (ID_PLANT_FACILITY) REFERENCES PLANT_FACILITY(ID),
    FOREIGN KEY (ID_PLANT_TYPE) REFERENCES PLANT_TYPE(ID)
);
GO

-- Tạo bảng ghi nhận sản lượng theo thời gian
CREATE TABLE PLANT_FACILITY_YIELD (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_PLANT_FACILITY INT NOT NULL, -- Mã cơ sở sản xuất
    MONTH INT NOT NULL, -- Tháng
    YIELD FLOAT NOT NULL, -- Sản lượng (đơn vị: kg, cây, ...)
    FOREIGN KEY (ID_PLANT_FACILITY) REFERENCES PLANT_FACILITY(ID)
);
GO

-- Tạo bảng cơ sở chế biến gỗ
CREATE TABLE WOOD_PROCESSING_FACILITY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    STATUS BIT NOT NULL, -- 0 OFF, 1 ON 
    ADDRESS NVARCHAR(255) NOT NULL,
    CONTACT_FACE NVARCHAR(100) NOT NULL, -- THÔNG TIN LIÊN HỆ
    CONTACT_MAIL NVARCHAR(100) NOT NULL, 
    CONTACT_PHONE NVARCHAR(100) NOT NULL,
    LABOR INT NOT NULL, -- SỐ NHÂN CÔNG 
    ACREAGE FLOAT NOT NULL, -- DIỆN TÍCH HECTA
    WOOD_SPECIES_PROVIDED NVARCHAR(500) NOT NULL, -- LOẠI GỖ ĐẦU VÀO 
    PRODUCT NVARCHAR(300) NOT NULL, -- SẢN PHẨM 
    IMAGE_WOOD_PROCESSING_FACILITY NVARCHAR(200), -- BẢN ĐỒ CƠ SỞ CHẾ BIẾN GỖ 
    ID_COMMUNE INT NOT NULL,
    FOREIGN KEY (ID_COMMUNE) REFERENCES COMMUNE(ID)
);
GO

-- Tạo bảng loại hình sản xuất
CREATE TABLE PRODUCTION_TYPE (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL -- TÊN LOẠI HÌNH SẢN XUẤT
);
GO

-- Tạo bảng liên kết loại hình sản xuất với cơ sở chế biến gỗ
CREATE TABLE PRODUCTION_TYPE_WOOD_PROCESSING_FACILITY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_WOOD_PROCESSING_FACILITY INT NOT NULL,
    ID_PRODUCTION_TYPE INT NOT NULL,
    FOREIGN KEY (ID_WOOD_PROCESSING_FACILITY) REFERENCES WOOD_PROCESSING_FACILITY(ID),
    FOREIGN KEY (ID_PRODUCTION_TYPE) REFERENCES PRODUCTION_TYPE(ID)
);
GO

-- Tạo bảng hình thức hoạt động
CREATE TABLE ACTIVITY_FORM (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL -- TÊN HÌNH THỨC HOẠT ĐỘNG
);
GO

-- Tạo bảng liên kết hình thức hoạt động với cơ sở chế biến gỗ
CREATE TABLE ACTIVITY_FORM_WOOD_PROCESSING_FACILITY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_WOOD_PROCESSING_FACILITY INT NOT NULL,
    ID_ACTIVITY_FORM INT NOT NULL,
    FOREIGN KEY (ID_WOOD_PROCESSING_FACILITY) REFERENCES WOOD_PROCESSING_FACILITY(ID),
    FOREIGN KEY (ID_ACTIVITY_FORM) REFERENCES ACTIVITY_FORM(ID)
);
GO

-- Tạo bảng thống kê cơ sở chế biến gỗ
CREATE TABLE WOOD_PROCESSING_STATISTICS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_WOOD_PROCESSING_FACILITY INT NOT NULL,
    MONTH INT NOT NULL, -- Tháng
    YIELD FLOAT NOT NULL, -- SẢN LƯỢNG
    FOREIGN KEY (ID_WOOD_PROCESSING_FACILITY) REFERENCES WOOD_PROCESSING_FACILITY(ID)
);
GO

-- Tạo bảng cơ sở lưu trữ động vật
CREATE TABLE ANIMAL_FACILITY (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    ADDRESS NVARCHAR(255),
    CONTACT_FACE NVARCHAR(100) NOT NULL, -- THÔNG TIN LIÊN HỆ
    CONTACT_MAIL NVARCHAR(100) NOT NULL, 
    CONTACT_PHONE NVARCHAR(100) NOT NULL,
    LABOR INT NOT NULL, -- SỐ NHÂN CÔNG 
    ACREAGE FLOAT NOT NULL, -- DIỆN TÍCH 
    IMAGE_ANIMAL_STORAGE NVARCHAR(200), -- bản đồ cơ sở lưu trữ động vật
    ID_COMMUNE INT NOT NULL,
    FOREIGN KEY (ID_COMMUNE) REFERENCES COMMUNE(ID)
);
GO

-- Tạo bảng động vật
CREATE TABLE ANIMAL (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    NAME NVARCHAR(100) NOT NULL,
    GENERIC INT NOT NULL, -- CHỦNG LOẠI
    DATE_FOUND DATE NOT NULL, -- NGÀY TÌM THẤY 
    PREVIOUS_QUANTITY INT NOT NULL, -- SỐ LƯỢNG CÁ THỂ
    STATUS INT, -- TRẠNG THÁI BẢO TỒN ( NGUY CẤP , ỔN ĐỊNH ,...) 
    HAS_FLUCTUATION BIT NOT NULL DEFAULT 0, -- 0: không có biến động, 1: có biến động
    CURRENT_QUANTITY INT NOT NULL -- SỐ LƯỢNG HIỆN TẠI
);
GO

CREATE TABLE FLUCTUATION (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_ANIMAL INT NOT NULL,
	TYPE BIT NOT NULL, -- LOẠI BIẾN ĐỘNG (TĂNG 1, GIẢM 0)
    DATE DATE NOT NULL, -- ngày biến động 
    REASON TEXT NOT NULL, -- LÝ DO BIẾN ĐỘNG 
    LOCATION NVARCHAR(255) NOT NULL, -- NƠI BIẾN ĐỘNG
    QUANTITY_CHANGE INT NOT NULL, -- SỐ LƯỢNG BIẾN ĐỘNG
    FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL(ID)
);
GO


-- Tạo bảng ghi nhận sản lượng động vật
CREATE TABLE ANIMAL_STATISTICS (
    ID INT IDENTITY(1,1) PRIMARY KEY,
    ID_ANIMAL INT NOT NULL,
    STATISTICS_DATE DATE NOT NULL, -- NGÀY THỐNG KÊ
    YIELD FLOAT NOT NULL, -- SẢN LƯỢNG
    FOREIGN KEY (ID_ANIMAL) REFERENCES ANIMAL(ID)
);
GO
